### ISSUE TITLE
关于初始化会战推送

### ISSUE THREAD

**Issue by beast27** [AddOneSecondL/pcrjjc2-clanbattle#15]
请问能不能直接在初始化会战推送环节加类似
output = open(output_path, 'w')
output.close()
这种代码。会不会出啥问题？

**Comment by AddOneSecondL** [comment]
换个变量名应该没啥大问题，然后如果在初始化那块做的话应该要改成全局的罢

**Comment by beast27** [comment]
我试了一下可以弄出一个新的Output.txt，既然没啥问题我就这么改了，不然每次进服务器删文件还挺麻烦。
