### ISSUE TITLE
大佬能做台服嘛

### ISSUE THREAD

**Issue by Mira19971102** [AddOneSecondL/pcrjjc2-clanbattle#16]
可以根据pcrjjc3做一个台服会战嘛？求一个

**Comment by AddOneSecondL** [comment]
不玩台服，不知道台服是啥样的ww

**Comment by Mira19971102** [comment]
大佬愿意研究一下嘛，，我愿意提供数据和pcrjjc3所需文件，我扣扣1486404395

**Comment by AddOneSecondL** [comment]
非常抱歉，由于精力有限我无法协助您完成台服部分的会战推送制作，但是看了一下pcrjjc3的文件，好像使用的api和国服是一样的，只是添加了区服的区分，您可以根据返回的数据来进一步制定台服的会战推送计划~

**Comment by Mira19971102** [comment]
好吧，谢谢
