### ISSUE TITLE
机器人时不时的抽风，不推送信息，需要敲几次回车才行，

### ISSUE THREAD

**Issue by wanli123a** [AddOneSecondL/pcrjjc2-clanbattle#22]
大佬，我又来提问题了，用着用着 后台就卡主不动了，然后没办法监控出刀记录什么的， 然后我发送了消息“会战状态”，然后在hoshino里面敲回车，然后机器人正常工作了，会补记录，这是我hoshino的问题吗？

代码如下所示
![image](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/134676781/2ae6ce05-8afc-4d09-804b-06a5879009b6)

**Comment by AddOneSecondL** [comment]
应该是，可能你的hos被什么阻塞了，或者被挂起了

**Comment by AddOneSecondL** [comment]
如果是windows看看有没有进入选择模式

**Comment by wanli123a** [comment]
我明白了！ 谢谢大佬，回复的太快了！  可能是我不小心点了 hos 的窗口了，进入选择模式了。  谢谢大佬！
