### ISSUE TITLE
登录后出现pcrclient: /clan/info api called pcrclient: /load/index api called 一直循环

### ISSUE THREAD

**Issue by qwe3107231** [AddOneSecondL/pcrjjc2-clanbattle#23]
![QQ图片20230526193635](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/73685785/0ad47f2b-aa9b-4a71-b26b-7793d47881d0)

**Comment by AddOneSecondL** [comment]
看起来像是陷入了某个循环

**Comment by AddOneSecondL** [comment]
试试重启，如果还是有相同的情况请在157行下方加个print(e)让我知道出了什么错误

**Comment by qwe3107231** [comment]
不好意思 原来是账号被踢出了公会233
