### ISSUE TITLE
会友又发现一个问题

### ISSUE THREAD

**Issue by duoshoumiao** [AddOneSecondL/pcrjjc2-clanbattle#24]
就是知道进去的人有多少，但是不知道在里面干嘛。 想要 一个 留言板功能
类似
![image](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/94856184/bf6a0516-ea59-40fc-b5ad-1e6ef047a1fe)
可随时取消留言那种

**Comment by AddOneSecondL** [comment]
可以有，不过获取不到是谁进去了，所以可能只能用群名称替代，最近事情比较多，可能所有意见都会在这期会战结束后加上ww

**Comment by duoshoumiao** [comment]
> 可以有，不过获取不到是谁进去了，所以可能只能用群名称替代，最近事情比较多，可能所有意见都会在这期会战结束后加上ww

嗯  最好是单独插件，不用设计在 这个会战通知插件里，方便更新的时候，群友也能知道，因为这期有人时停被 滑了一刀  发现了这个问题，对了 你是用什么app回复的，这么快

**Comment by AddOneSecondL** [comment]
啊，github好像是有个手机app来着

**Comment by AddOneSecondL** [comment]
还有一些自用功能比如生成box图和装备统计什么的，不太好往上加

**Comment by duoshoumiao** [comment]
> 还有一些自用功能比如生成box图和装备统计什么的，不太好往上加

确实

**Comment by duoshoumiao** [comment]
这期图片版 直接严重风控  惨案  还是得文字版

**Comment by AddOneSecondL** [comment]
account里面会战状态有文字版来着，上期好像加的，不过最近tx确实抽的厉害，好悬没给我bot踹开线

**Comment by AddOneSecondL** [comment]
会战本来消息就多

**Comment by duoshoumiao** [comment]
简直寄  刚换上新qq 也没坚持住几分钟

**Comment by AddOneSecondL** [comment]
风控挺玄学，不知道是检测重复字数还是啥，如果是重复字数的话倒是可以改改格式

**Comment by AddOneSecondL** [comment]
估计只能等gocq那边的大佬们研究出解决方案了

**Comment by duoshoumiao** [comment]
手表登陆的都风控了  其他的只要不换协议就不会出事

**Comment by AddOneSecondL** [comment]
今天才手表换MAC，不知道能撑多久

**Comment by AddOneSecondL** [comment]
可以，我也借鉴一下，这垃圾代码也不怕叠多高了，之前所有要改的大概会战结束后会加进来

**Comment by duoshoumiao** [comment]
没问题  我为了应对风控 手头有4个备用qq

**Comment by duoshoumiao** [comment]
收不到私聊的qq怎么办

**Comment by AddOneSecondL** [comment]
验证收不到？改群聊罢

**Comment by duoshoumiao** [comment]
> 验证收不到？改群聊罢

怎么改

**Comment by AddOneSecondL** [comment]
稍等一下，马上更新

**Comment by duoshoumiao** [comment]
手表协议可以收到  但是最近手表会风控

**Comment by AddOneSecondL** [comment]
试试这样，用最新更改的那部分，然后account里面填上captcha_group，就是发送的群，然后获取链接后私聊bot提交试试

**Comment by duoshoumiao** [comment]
好

**Comment by duoshoumiao** [comment]
![Screenshot_20230601-135843.jpg](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/94856184/b776552e-f074-4666-af4f-35d22a21fe8e)

**Comment by AddOneSecondL** [comment]
事captcha_group,写少了

**Comment by duoshoumiao** [comment]
> 事captcha_group,写少了
> 

要加［ 吗］

**Comment by AddOneSecondL** [comment]
就是67行群聊那条group_id = acinfo["captcha_group"]，account里面不需要括号，填一个群号就行

**Comment by duoshoumiao** [comment]
![image](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/94856184/06df50c1-4c52-44f0-9506-7bb2a7da3698)
![%8~G$8FOCGM0`PATS0ECIG4](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/94856184/aad2fa33-264f-4220-83af-c067c993eb65)

**Comment by AddOneSecondL** [comment]
看看报错，可能是会战结束后没整到排名数据，那边没写跳过

**Comment by duoshoumiao** [comment]
![image](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/94856184/76e38f95-31b8-4d47-a538-a41ecc4d8af4)

**Comment by duoshoumiao** [comment]
我换成  抓人。也不行

**Comment by duoshoumiao** [comment]
![image](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/94856184/cd3b5a54-b13f-4107-8a46-8fe376ea684a)
好不容易chu'lai出来了 是个空白的

**Comment by AddOneSecondL** [comment]
这个情况好像是验证码过期了

**Comment by AddOneSecondL** [comment]
我找找pcrjjc2的更新

**Comment by duoshoumiao** [comment]
OK

**Comment by AddOneSecondL** [comment]
我看到更新里面有一个”为避免tx网页安全验证使验证码过期，请手动拼接链接头和链接'“，会不会是这个问题

**Comment by duoshoumiao** [comment]
只有重启第一次 喊 抓人会弹出 验证码  后面无论几次都没有

**Comment by AddOneSecondL** [comment]
麻烦你再试试新的这个，排除一下是不是tx这个安全验证的问题

**Comment by duoshoumiao** [comment]
> 麻烦你再试试新的这个，排除一下是不是tx这个安全验证的问题

可以了  感谢

**Comment by AddOneSecondL** [comment]
真玄学锕，以前不是没这种事的嘛

**Comment by AddOneSecondL** [comment]
我看pcrjjc2好像加了个本地部署的验证码，到时候借鉴过来看看

**Comment by duoshoumiao** [comment]
> 真玄学锕，以前不是没这种事的嘛

可能输错就不会再发一次验证码了。不过登录一次就一劳永逸

**Comment by AddOneSecondL** [comment]
理论上来说输错一次会重新发，可能当时删这个验证码的时候哪部分多删了

**Comment by duoshoumiao** [comment]
希望 预约功能 加个留言，  “会战状态”可以显示那种。

**Comment by AddOneSecondL** [comment]
在做了在做了，先把期末的事情整完先，这个好整

**Comment by duoshoumiao** [comment]
泰裤辣

**Comment by duoshoumiao** [comment]
![image](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/94856184/0a82f9a5-07d9-4b78-b1cb-843d1ac1703b)

**Comment by AddOneSecondL** [comment]
会战还没开，无法获得boss信息，理论上这个信息获取应该要被跳过

**Comment by duoshoumiao** [comment]
输入状态会显示留言吗，我还不知道怎么取消留言

**Comment by AddOneSecondL** [comment]
还在写，之前没写完保存了一下

**Comment by duoshoumiao** [comment]
哦哦

**Comment by duoshoumiao** [comment]
会战状态  这条指令可以查看留言了吗  没到会战期间看不到

**Comment by AddOneSecondL** [comment]
还不能，暂时不知道放哪，打算简化一下图片的，现在只能用留言板看到

**Comment by duoshoumiao** [comment]
不能自动报刀了，图片版也发不出来了

**Comment by duoshoumiao** [comment]
![IMG_20230625_052404.jpg](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/94856184/a7a76106-9f6f-41fb-adba-03ab188ad865)

**Comment by AddOneSecondL** [comment]
号还在会里嘛，看看是哪部分出的问题

**Comment by AddOneSecondL** [comment]
然后看看推送群填了没

**Comment by duoshoumiao** [comment]
打到b面他又能报了 是不是a面有什么问题

**Comment by AddOneSecondL** [comment]
好奇怪，我这A没问题

**Comment by AddOneSecondL** [comment]
top那个api获取失败的话大概率应该是会战币没更新

**Comment by duoshoumiao** [comment]
图片不知道还能不能发 号在会里

**Comment by duoshoumiao** [comment]
> 然后看看推送群填了没

嗯  填了

**Comment by AddOneSecondL** [comment]
状态好像是782行有个变量错了

**Comment by duoshoumiao** [comment]
![226422a27be5ffe.png](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/94856184/d9dc9d00-b68e-4634-b069-83a9eecf710c)

**Comment by duoshoumiao** [comment]
> ![226422a27be5ffe.png](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/94856184/d9dc9d00-b68e-4634-b069-83a9eecf710c)
> 
> 

发送状态会弹这个错误

**Comment by AddOneSecondL** [comment]
挺奇怪，这边正常，我找找哪出问题了

**Comment by duoshoumiao** [comment]
> 挺奇怪，这边正常，我找找哪出问题了

文字版没有问题  图片版发不出来

**Comment by AddOneSecondL** [comment]
这边图片文字都没问题，还在等他们打找找原因

**Comment by duoshoumiao** [comment]
![-331c2fbc05e98076.png](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/94856184/d1ca67a4-489d-4423-9ca9-4ea88cae81e9)

**Comment by AddOneSecondL** [comment]
可能是文件编码问题

**Comment by AddOneSecondL** [comment]
这个py文件应该是用UTF-8的吧，确认一下

**Comment by duoshoumiao** [comment]
嗯嗯

**Comment by duoshoumiao** [comment]
![image](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/94856184/bb1ab5a5-93a3-4183-940d-bcea5e0cd2de)

**Comment by AddOneSecondL** [comment]
清空一下output再试试，用记事本来存数据还是太抽象了，有时间改成数据库吧

**Comment by duoshoumiao** [comment]
好的

**Comment by AddOneSecondL** [comment]
> ![-331c2fbc05e98076.png](https://user-images.githubusercontent.com/94856184/248569350-d1ca67a4-489d-4423-9ca9-4ea88cae81e9.png)

噢对了，也检查一下编码问题吧

**Comment by AddOneSecondL** [comment]
b记事本存东西问题太大了

**Comment by duoshoumiao** [comment]
> 清空一下output再试试，用记事本来存数据还是太抽象了，有时间改成数据库吧

还是不行

**Comment by duoshoumiao** [comment]
图片版会出现这个问题

**Comment by AddOneSecondL** [comment]
是用UTF-8保存的嘛

**Comment by duoshoumiao** [comment]
我还没更新状态前就有这个问题，都没去改过，不知道为什么突然就不能发图片了

**Comment by AddOneSecondL** [comment]
这边应该是从记事本读出刀信息没读出来，可以试试改一下记事本的编码，如果实在不行可以试试另一个大佬做的那个会战推送，好像挺不错的

**Comment by duoshoumiao** [comment]
> 是用UTF-8保存的嘛

对

**Comment by duoshoumiao** [comment]
> 这边应该是从记事本读出刀信息没读出来，可以试试改一下记事本的编码，如果实在不行可以试试另一个大佬做的那个会战推送，好像挺不错的

感谢大佬  可以发出来了
