### ISSUE TITLE
发送“会战状态”后控制台输出“different loop”

### ISSUE THREAD

**Issue by HHEBL** [AddOneSecondL/pcrjjc2-clanbattle#26]
<img width="507" alt="issu" src="https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/64397778/3a7bbdd1-7116-4d94-811d-5175b2f6a72c">
如图，在会战结束的状态下，向机器人发送“会战状态”，后台在试图登录账号的过程中输出如下报错，随之而来的还有反复的“maximum number of…”。求问大佬这是怎么回事，是因为会战结束了这样还是我没有配置好呢？

**Comment by AddOneSecondL** [comment]
验证没过，卡住了，而且会战推送在开启状态，每次定时任务都会显示这个

**Comment by AddOneSecondL** [comment]
尝试重启后过一遍验证码应该就能解决

**Comment by HHEBL** [comment]
又遇到了新的情况，大佬你看看我这个步骤有没有问题：
1. account.json里captcha_group添加了群号
2. 群里发送“会战状态”，机器人发送验证码链接
3. 进入链接，完成验证，复制了validate=后面的内容，按/pcrvalclan xxxx格式私聊机器人，我添了两个print看了一下，机器人是准确收到了那串码的
4. 再次向机器人发送“会战状态”，仍提示“账号被风控，请联系管理员……”
5. 我还尝试过按1-3步骤操作，然后关闭hoshinoBot，再启动hoshinoBot，群里发送“会战状态”，机器人仍是发送验证码链接要求验证。

**Comment by AddOneSecondL** [comment]
显示账号被风控说明还在验证状态，validating那个变量还是true，有没有更详细的记录

**Comment by HHEBL** [comment]
<img width="1280" alt="333" src="https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/64397778/6959dd96-d1f9-4a59-b100-9c7ecd248197">
<img width="506" alt="222" src="https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/64397778/c14c8684-ae44-4aa6-9dbd-fd60b21f68c1">
<img width="506" alt="111" src="https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/64397778/d549399e-c9ba-4cca-8d68-04a41deff9cc">

第一张是我加的两个print，第二张是我私聊机器人validate后print的输出，第三张是完成验证后再发送“会战状态”后台的提示

**Comment by czt346** [comment]
你好作者，我也是一样的问题，不能自动过码，会一直循环显示“尝试自动过码1次”，并且不能自行切换手动过码。通过修改        82行while ccnt < 10值改为1,bot就能切换到手动过码，但在把码发给bot会继续“尝试自动过码1次”，如此循环。

**Comment by AddOneSecondL** [comment]
那先回到以前版本吧，我再看看

**Comment by AddOneSecondL** [comment]
> 你好作者，我也是一样的问题，不能自动过码，会一直循环显示“尝试自动过码1次”，并且不能自行切换手动过码。通过修改 82行while ccnt < 10值改为1,bot就能切换到手动过码，但在把码发给bot会继续“尝试自动过码1次”，如此循环。

试试这个bsgamesdk.py

**Comment by czt346** [comment]
感谢作者，现在手动过码已经解决了。过码后重启bot也能自动登录。
