### ISSUE TITLE
目前查不了档线吗

### ISSUE THREAD

**Issue by duoshoumiao** [AddOneSecondL/pcrjjc2-clanbattle#3]
一直显示数据错误

**Comment by AddOneSecondL** [comment]
更新一下插件

**Comment by duoshoumiao** [comment]
> 更新一下插件

我刚更新

**Comment by AddOneSecondL** [comment]
把735和964的try except去掉看看是什么错误，我这渣代码是这样的

**Comment by duoshoumiao** [comment]
> 把735和964的try except去掉看看是什么错误，我这渣代码是这样的

位置不对 最高950

**Comment by AddOneSecondL** [comment]
那就720和948的

**Comment by duoshoumiao** [comment]
> 那就720和948的

就没反应 了
![JBBZ KWEUA%JS ITVDSZ7(5](https://user-images.githubusercontent.com/94856184/230750578-e6fe5de9-e0ee-43cd-8c18-b5966f932a90.gif)

**Comment by AddOneSecondL** [comment]
948的except改成这样式
`    except Exception as e:
        print(e)`
应该就能显示哪出错力

**Comment by duoshoumiao** [comment]
> except Exception as e: print(e)

这个插件支持新版hos吗

**Comment by AddOneSecondL** [comment]
应该支持吧，我用的是12月份的hos

**Comment by duoshoumiao** [comment]
> 应该支持吧，我用的是12月份的hos

![image](https://user-images.githubusercontent.com/94856184/230751215-3d3f6c52-7e8f-491b-8570-710730aaec66.png)

**Comment by AddOneSecondL** [comment]
re是正则匹配吧，init里面有没有import re

**Comment by AddOneSecondL** [comment]
我的锅，我忘了import re力

**Comment by duoshoumiao** [comment]
> 我的锅，我忘了import re力

可以了

**Comment by AddOneSecondL** [comment]
qwq
