### ISSUE TITLE
大佬为啥有时候记录的Output里会丢刀啊

### ISSUE THREAD

**Issue by yuban01652** [AddOneSecondL/pcrjjc2-clanbattle#36]
对比记录的Output.txt和b站的工具箱数据，有时会发现Output.txt里面会跳过一刀
即会战工具箱里按时间显示“刀1” “刀2” “刀3”，Output.txt里面只能看见“刀1” “刀3”，“刀2”的数据被跳过了
好像也没啥报错信息，统计的时候发现少了一刀，查工具箱才发现
这是啥bug，有没有啥办法让插件能检查一下记录数据对不对啊_(:з」∠)_

**Comment by AddOneSecondL** [comment]
https://github.com/SonderXiaoming/kanna_connection_redive
一样的，主要是游戏内无法统计满补刀，如果出了满补会出现计算出错

**Comment by yuban01652** [comment]
诶，大佬，不是查刀时计算少刀，而是Output.txt里面就没有这一刀的数据，这也是满补计算的错误么？

**Comment by AddOneSecondL** [comment]
开摆力，建议用上面那个大佬的项目

**Comment by yuban01652** [comment]
好吧_(:з」∠)_感谢大佬这些时间的贡献
