### ISSUE TITLE
求助ERROR: Incorrect AES key length (0 bytes)

### ISSUE THREAD

**Issue by 964788339** [AddOneSecondL/pcrjjc2-clanbattle#37]
这期想着好就没更新插件更新了一下
发送会战状态时报错
![6OZOZX0ZANV18~Z)%}L%6U5](https://github.com/AddOneSecondL/pcrjjc2-clanbattle/assets/61876981/c3b967d9-627d-42e5-8dcf-d0d2cd8862c5)

**Comment by AddOneSecondL** [comment]
pcrclient.py 注释掉 await self.callapi('/check/check_agreement', {})

**Comment by 964788339** [comment]
感谢！
