### ISSUE TITLE
注释掉 await self.callapi(...) 后发送“会战状态”HoshinoBot闪退

### ISSUE THREAD

**Issue by HHEBL** [AddOneSecondL/pcrjjc2-clanbattle#39]
大佬，上一个问题里那个await self.callapi('/check/check_agreement', {})，不注释时请求“会战状态”会报AES key错误，注释掉后请求“会战状态”就会直接闪退了，这是咋回事呀，报错信息也没有……
另外在启动项目时有一个报错，不知道和我的问题有没有关系：
HoshinoBot\hoshino\modules\pcrjjc2-clanbattle\pcrclient.py:194: SyntaxWarning: invalid escape sequence '\d'
  match = search('\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d', manifest['maintenance_message']).group()

**Comment by AddOneSecondL** [comment]
不到啊，我也好久没维护这个项目了，建议换另一个大佬的推送，那个代码力比这强
https://github.com/SonderXiaoming/kanna_connection_redive

另外这个是警告应该跟这个没太大关系，别的地方出问题了

**Comment by HHEBL** [comment]
好的好的，谢谢大佬了

**Comment by HHEBL** [comment]
经过大佬的指点，发现与是否注释掉 await self.callapi('/check/check_agreement', {}) 无关，闪退是因为pillow库版本过高，回退到6.2.1版本即可正常使用。
