### ISSUE TITLE
头像全是白的

### ISSUE THREAD

**Issue by koudaiai** [AddOneSecondL/pcrjjc2-clanbattle#7]
![QQ图片20230424075956](https://user-images.githubusercontent.com/74299446/233873677-c51b6877-6591-4e38-85b6-957eef36e204.jpg)
res文件也下了，HoshinoBot的__bot__.py也改了，就是显示不了，小白表示头大

**Comment by AddOneSecondL** [comment]
尝试更新或者在最开始加上from hoshino import R，这个是我的问题，不知道啥时候R丢了

**Comment by koudaiai** [comment]
> 尝试更新或者在最开始加上from hoshino import R，这个是我的问题，不知道啥时候R丢了

可以了，谢谢大佬
