### ISSUE TITLE
出现错误KeyError: 90006

### ISSUE THREAD

**Issue by Rlezzo** [AddOneSecondL/pcrjjc2-clanbattle#8]
![QQ截图20230424153436](https://user-images.githubusercontent.com/86238734/233929652-98974feb-92cc-4766-abd6-d4c444df2890.png)
请问是什么问题

**Comment by AddOneSecondL** [comment]
没有会战币吗？我好像没有把没有把库存里面没有会战币这个情况考虑到

**Comment by AddOneSecondL** [comment]
嗯嗯
